language: node_js

node_js: "stable"

install: npm install

services:
  - postgresql

before_script:
  - psql -c 'create database teamwork_test;' -U postgres

scripts: 
  - npm test
  - psql -c 'select * from users;' -U postgres


after_script: npm run coveralls